### ISSUE TITLE
How did you get into programming?

### ISSUE THREAD

**Issue by sindresorhus** [najela/ama#8]

**Comment by najela** [comment]
I had big problems with money when I was young since my parents didn't really make much. I  Learned the richest man in the world was Bill Gates and he had enough money to feed my whole country for like a year (*probably more*). I got interested in him and I discovered he was a programmer and stuff.  This is what got me into computers and tech in general.

What really got me into programming and computer science is the racebook Story. I wanted to be the next Mark Zuckerberg
