### ISSUE TITLE
How is it like being a programmer in Africa?

### ISSUE THREAD

**Issue by sindresorhus** [najela/ama#9]

**Comment by najela** [comment]
Well its kind of fascinating.

You can't really tell your friends that you're a programmer since they don't even know what programming is. Its hard to too collaborate on a project since you can't really meet other programmers to work with. Internet is crapy so at times googling a problem becomes another problem. When most people see a terminal window, they know you're about to hack a bank so they become your friend or they beg you to give hack a telecoms company so they can get free internet. 

>But things are changing for the better
